/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-background": "#001a42",
          "grass-block": "#66BB6A",
          "secondary": "#77574d",
          "text-primary": "#5D4037",
          "inverse-on-surface": "#edf0ff",
          "cube-blue": "#448AFF",
          "surface-dim": "#cbdaff",
          "surface-container-lowest": "#ffffff",
          "tertiary": "#006c45",
          "on-tertiary-fixed": "#002112",
          "surface-container": "#e9edff",
          "on-tertiary-fixed-variant": "#005233",
          "on-secondary": "#ffffff",
          "surface-bright": "#f9f9ff",
          "surface-container-high": "#e0e8ff",
          "on-tertiary-container": "#007c50",
          "on-surface": "#001a42",
          "outline-variant": "#c5c6cc",
          "surface-container-low": "#f1f3ff",
          "on-secondary-container": "#795950",
          "inverse-surface": "#002e6a",
          "on-error": "#ffffff",
          "tertiary-fixed-dim": "#55de9e",
          "outline": "#75777c",
          "on-primary-fixed": "#141c26",
          "tertiary-fixed": "#75fbb8",
          "error-container": "#ffdad6",
          "primary-fixed": "#dbe3f1",
          "background": "#E8F0FE",
          "surface-tint": "#575f6b",
          "secondary-fixed-dim": "#e7bdb1",
          "on-primary": "#ffffff",
          "on-error-container": "#93000a",
          "surface-container-highest": "#d8e2ff",
          "inverse-primary": "#bfc7d4",
          "on-secondary-fixed": "#2c160e",
          "secondary-fixed": "#ffdbd0",
          "on-tertiary": "#ffffff",
          "secondary-container": "#fed3c7",
          "primary-fixed-dim": "#bfc7d4",
          "surface": "#f9f9ff",
          "lava-orange": "#FF7043",
          "on-secondary-fixed-variant": "#5d4037",
          "on-surface-variant": "#44474b",
          "accent-interactive": "#69F0AE",
          "primary-container": "#e8f0fe",
          "error": "#ba1a1a",
          "on-primary-fixed-variant": "#3f4752",
          "on-primary-container": "#656d79",
          "surface-variant": "#d8e2ff",
          "tertiary-container": "#b9ffd5",
          "primary": "#575f6b"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "base-unit": "0.5rem",
          "gutter": "1.5rem",
          "section-gap": "clamp(4rem, 8vw, 8rem)",
          "max-width": "1280px"
      },
      "fontFamily": {
          "metadata": ["JetBrains Mono", "monospace"],
          "label-sm": ["Nunito Sans", "sans-serif"],
          "headline-h1": ["Nunito Sans", "sans-serif"],
          "body-md": ["Nunito", "sans-serif"],
          "h1": ["Nunito", "sans-serif"],
          "hero": ["Nunito Sans", "sans-serif"],
          "headline-h2": ["Nunito Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
